version: "3.7"
services:
    nginx:
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/sites-available/default
        ports:
            - 80:80
        container_name: cst-nginx
        depends_on:
            - web
            - api
    web:
        build:
            dockerfile: ./client/Dockerfile
        ports:
            - 3000:3000
        container_name: cst-web
    api:
        build: .
        ports:
            - 8080:8080
        container_name: cst-api
    mariadb:
        image: mariadb:10.9
        ports:
            - 3306:3306
        volumes:
            - ./db/conf.d:/etc/mysql/conf.d
            - ./db/data:/var/lib/mysql
            - ./db/initdb.d:/docker-entrypoint-initdb.d
        restart: always
        env_file: ./db/.env
        environment:
                TZ: Asia/Seoul
        container_name: cst-db



