version: "3.7"
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        container_name: cst-nginx
        image: jparangdev/32devs:cst-nginx
        depends_on:
            - web
            - api
        extra_hosts:
            - "host.docker.internal:host-gateway"
    web:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        container_name: cst-web
        image: jparangdev/32devs:cst-web
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        container_name: cst-api
        image: jparangdev/32devs:cst-api
