FROM openjdk:11
RUN mkdir "/app"
WORKDIR "/app"
RUN mkdir "backend"
COPY build/libs/app.jar /app/backend/app.jar
RUN apt update && apt install nginx -y
RUN mkdir "frontend"
COPY client/build /app/frontend
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
EXPOSE 8080
CMD ["java","-jar","/app/backend/app.jar"]
