version: "3.7"
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        container_name: cst-nginx
#        depends_on:
#            - web
#            - api
    web:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        container_name: cst-web
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        container_name: cst-api
        depends_on:
            - mariadb
    mariadb:
        build:
            context: ./mariaDB
            dockerfile: Dockerfile
        ports:
            - "3306:3306"
        restart: always
        container_name: cst-db
