version: "3.7"
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 80:80
        container_name: cst-nginx
        depends_on:
            - web
            - api
    web:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        container_name: cst-web
    api:
        build:
            context: .
            dockerfile: DockerFile
        ports:
            - 8080:8080
        container_name: cst-api
        depends_on:
            - mariadb
    mariadb:
        image: mariadb:10.9
        ports:
            - 3306:3306
        volumes:
            - ./db/conf.d:/etc/mysql/conf.d
            - ./db/data:/var/lib/mysql
            - ./db/initdb.d:/docker-entrypoint-initdb.d
        restart: always
        env_file: ./db/.env
        environment:
                TZ: Asia/Seoul
        container_name: cst-db




