# CircleCI configuration file

version: 2.1

jobs:
    build:
        docker:
            - image: circleci/openjdk:11-jdk
        working_directory: ~/repo

        environment:
            JVM_OPTS: -Xmx3200m
            TERM: dumb

        steps:
            - checkout
            - run: gradle bootJar
            - run:
                name: Install Docker Compose
                environment:
                    COMPOSE_VERSION: '1.29.2'
                command: |
                    curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
                    chmod +x ~/docker-compose
                    sudo mv ~/docker-compose /usr/local/bin/docker-compose
            - setup_remote_docker
            - run:
                name: Build images of services declared in docker-compose.yml
                command: docker-compose build
            - run:
                name: push docker compose
                command: docker-compose push
